//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBonApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtikelBon
    {
        public long ArtikelID { get; set; }
        public long BonID { get; set; }
        public Nullable<long> Aantal { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Bon Bon { get; set; }
    }
}
