//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;

namespace WpfBonApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDBEntities : DbContext
    {
        //public myDBEntities()
        //    : base("name=myDBEntities")
        //{
        //}
        public myDBEntities()
            : base(ConnectionString())
        {
        }


        private static string ConnectionString()
        {
            SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder();
            sqlBuilder.DataSource = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\Bon App\\myDB.db";
            //sqlBuilder.InitialCatalog = "YYY";
            //sqlBuilder.PersistSecurityInfo = true;
            //sqlBuilder.IntegratedSecurity = true;
            sqlBuilder.MultipleActiveResultSets = true;

            EntityConnectionStringBuilder entityBuilder = new EntityConnectionStringBuilder();
            entityBuilder.ProviderConnectionString = sqlBuilder.ToString();
            entityBuilder.Metadata = "res://*/Model.ModelBon.csdl|res://*/Model.ModelBon.ssdl|res://*/Model.ModelBon.msl";
            entityBuilder.Provider = "System.Data.SQLite.EF6";

            return entityBuilder.ToString();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikel> Artikels { get; set; }
        public virtual DbSet<ArtikelBon> ArtikelBons { get; set; }
        public virtual DbSet<Bon> Bons { get; set; }
        public virtual DbSet<Gebruiker> Gebruikers { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
    }
}
